# Generated by Django 4.2.10 on 2026-05-20 07:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroSesion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio_sesion', models.DateTimeField(auto_now_add=True)),
                ('fin_sesion', models.DateTimeField(blank=True, null=True)),
                ('duracion_minutos', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('activa', models.BooleanField(default=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sesiones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro de Sesión',
                'verbose_name_plural': 'Registros de Sesiones',
                'ordering': ['-inicio_sesion'],
            },
        ),
    ]
