# Generated by Django 4.2.10 on 2026-05-07 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entidades', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recomendacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('reduccion_estimada', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Reducción estimada (tCO₂e/año)')),
                ('costo_referencial', models.CharField(blank=True, max_length=100, verbose_name='Costo referencial (COP)')),
                ('viabilidad', models.CharField(choices=[('ALTA', 'Alta'), ('MEDIA', 'Media'), ('BAJA', 'Baja')], default='MEDIA', max_length=10)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_ESTUDIO', 'En estudio'), ('EN_EJECUCION', 'En ejecución'), ('IMPLEMENTADA', 'Implementada')], default='PENDIENTE', max_length=20)),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('entidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recomendaciones', to='entidades.entidad')),
            ],
            options={
                'verbose_name': 'Recomendación',
                'verbose_name_plural': 'Recomendaciones',
                'ordering': ['-reduccion_estimada'],
            },
        ),
    ]
