# Generated by Django 4.2.10 on 2026-05-07 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entidades', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alcance', models.IntegerField(choices=[(1, 'Alcance 1 — Emisiones directas (combustibles)'), (2, 'Alcance 2 — Energía eléctrica'), (3, 'Alcance 3 — Residuos y transporte')], verbose_name='Alcance GHG')),
                ('año', models.IntegerField(verbose_name='Año')),
                ('mes', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12')], verbose_name='Mes')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Cantidad consumida')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('entidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumos', to='entidades.entidad')),
            ],
            options={
                'verbose_name': 'Consumo',
                'verbose_name_plural': 'Consumos',
                'ordering': ['-año', '-mes'],
            },
        ),
        migrations.CreateModel(
            name='FactorEmision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=100, verbose_name='Categoría')),
                ('subcategoria', models.CharField(max_length=100, verbose_name='Subcategoría')),
                ('valor', models.DecimalField(decimal_places=6, max_digits=10, verbose_name='Factor (kgCO2e/unidad)')),
                ('unidad', models.CharField(max_length=50, verbose_name='Unidad del consumo')),
                ('fuente', models.CharField(max_length=200, verbose_name='Fuente (IPCC/UPME)')),
                ('año_referencia', models.IntegerField(default=2021, verbose_name='Año de referencia')),
            ],
            options={
                'verbose_name': 'Factor de emisión',
                'verbose_name_plural': 'Factores de emisión',
                'ordering': ['categoria', 'subcategoria'],
            },
        ),
        migrations.CreateModel(
            name='Emision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tco2e', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='Emisiones (tCO₂e)')),
                ('factor_usado', models.DecimalField(decimal_places=6, max_digits=10, verbose_name='Factor aplicado')),
                ('fecha_calculo', models.DateTimeField(auto_now_add=True)),
                ('consumo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='emision', to='consumos.consumo')),
            ],
            options={
                'verbose_name': 'Emisión calculada',
                'verbose_name_plural': 'Emisiones calculadas',
            },
        ),
        migrations.AddField(
            model_name='consumo',
            name='factor_emision',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='consumos.factoremision', verbose_name='Tipo de consumo'),
        ),
        migrations.AlterUniqueTogether(
            name='consumo',
            unique_together={('entidad', 'factor_emision', 'año', 'mes')},
        ),
    ]
