# Generated by Django 4.2.10 on 2026-05-07 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('departamento', models.CharField(default='Cundinamarca', max_length=100)),
            ],
            options={
                'verbose_name': 'Municipio',
                'verbose_name_plural': 'Municipios',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Entidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre de la entidad')),
                ('tipo', models.CharField(choices=[('ALCALDIA', 'Alcaldía'), ('SECRETARIA', 'Secretaría'), ('EMPRESA', 'Empresa pública'), ('OTRO', 'Otro')], default='ALCALDIA', max_length=20, verbose_name='Tipo de entidad')),
                ('nit', models.CharField(max_length=20, unique=True, verbose_name='NIT')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entidades', to='entidades.municipio', verbose_name='Municipio')),
            ],
            options={
                'verbose_name': 'Entidad',
                'verbose_name_plural': 'Entidades',
                'ordering': ['nombre'],
            },
        ),
    ]
